const dict={
en:{navServices:"Services",navAbout:"About us",navWhy:"Why DUVERO",navContact:"Contact",quote:"Get a quote",heroTitle:"GLOBAL FREIGHT<br>& LOGISTICS",heroCopy:"Flexible freight solutions built around your business — across borders, modes and markets.",explore:"Explore services",sea:"Flexible ocean freight for global supply chains.",air:"Fast solutions when timing matters.",road:"Reliable transport across Europe and beyond.",warehouse:"Scalable storage and handling solutions.",customs:"Practical support that keeps cargo moving.",aboutTitle:"A STRONGER TOMORROW, TOGETHER.",aboutText:"DUVERO is built around a simple idea: logistics should feel personal, responsive and straightforward. We connect businesses and markets through flexible freight solutions and long-term partnerships.",people:"Personal service",progress:"Forward thinking",partner:"Long-term focus",whyTitle:"LOGISTICS WITHOUT THE NOISE.",w1t:"One point of contact",w1:"Clear communication from quote to delivery.",w2t:"Flexible by design",w2:"Solutions shaped around the shipment — not the other way around.",w3t:"Built for partnerships",w3:"A long-term mindset focused on your business.",quoteTitle:"LET'S FIND THE RIGHT ROUTE.",quoteCopy:"Tell us about your shipment. We’ll use the details to understand your request.",name:"Name",company:"Company",phone:"Phone",from:"From",to:"To",service:"Service",details:"Shipment details",send:"Prepare email request",privacy:"Your details are only used to respond to your enquiry.",contactText:"Ready to discuss a shipment or partnership? Get in touch.",contactNote:"Add your registered address, phone number and CVR/VAT number here before launch."},
da:{navServices:"Ydelser",navAbout:"Om os",navWhy:"Hvorfor DUVERO",navContact:"Kontakt",quote:"Få et tilbud",heroTitle:"GLOBAL FREIGHT<br>& LOGISTICS",heroCopy:"Fleksible transportløsninger bygget omkring din forretning — på tværs af grænser, transportformer og markeder.",explore:"Se vores ydelser",sea:"Fleksibel søfragt til globale forsyningskæder.",air:"Hurtige løsninger, når tiden er afgørende.",road:"Pålidelig vejtransport i Europa og videre.",warehouse:"Skalerbare lager- og håndteringsløsninger.",customs:"Praktisk hjælp, der holder godset i bevægelse.",aboutTitle:"EN STÆRKERE FREMTID, SAMMEN.",aboutText:"DUVERO bygger på en enkel idé: logistik skal være personlig, fleksibel og ligetil. Vi forbinder virksomheder og markeder gennem fleksible transportløsninger og langsigtede partnerskaber.",people:"Personlig service",progress:"Fremadrettet",partner:"Langsigtet fokus",whyTitle:"LOGISTIK UDEN STØJ.",w1t:"Én kontaktperson",w1:"Klar kommunikation fra tilbud til levering.",w2t:"Fleksibel fra starten",w2:"Løsninger tilpasset forsendelsen — ikke omvendt.",w3t:"Bygget til partnerskaber",w3:"Et langsigtet fokus på din forretning.",quoteTitle:"LAD OS FINDE DEN RIGTIGE RUTE.",quoteCopy:"Fortæl os om din forsendelse, så vi kan forstå dit behov.",name:"Navn",company:"Virksomhed",phone:"Telefon",from:"Fra",to:"Til",service:"Ydelse",details:"Forsendelsesdetaljer",send:"Klargør mailforespørgsel",privacy:"Dine oplysninger bruges kun til at besvare din henvendelse.",contactText:"Skal vi tale om en forsendelse eller et samarbejde? Kontakt os.",contactNote:"Tilføj registreret adresse, telefonnummer og CVR/VAT-nummer her før lancering."}};
let lang="en";const langBtn=document.getElementById("lang");
function apply(){document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(el=>{let v=dict[lang][el.dataset.i18n];if(v!==undefined)el.innerHTML=v});langBtn.textContent=lang==="en"?"DA":"EN"}
langBtn.onclick=()=>{lang=lang==="en"?"da":"en";apply()};
const hamb=document.querySelector(".hamb"),nav=document.getElementById("nav");hamb.onclick=()=>{nav.classList.toggle("open");hamb.setAttribute("aria-expanded",nav.classList.contains("open"))};
document.getElementById("year").textContent=new Date().getFullYear();
document.getElementById("quoteForm").addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target);const subject=encodeURIComponent("Freight enquiry - "+(f.get("company")||f.get("name")));const body=encodeURIComponent(`Name: ${f.get("name")}\nEmail: ${f.get("email")}\nCompany: ${f.get("company")}\nPhone: ${f.get("phone")}\nFrom: ${f.get("from")}\nTo: ${f.get("to")}\nService: ${f.get("service")}\n\nShipment details:\n${f.get("details")}`);window.location.href=`mailto:info@duveroglobal.com?subject=${subject}&body=${body}`});
apply();